### ISSUE TITLE
ruby_deps?

### ISSUE THREAD

**Issue by Veidit** [erasme/ansible-ruby-compiled#1]
In https://github.com/erasme/ansible-ruby-compiled/blob/master/tasks/common-prereqs.yml :6 we see:
  with_items: ruby_deps

But where are ruby_deps defined?

I currently get this error:
TASK: [erasme.ruby-compiled | Installs ruby building dependencies] ***********\* 
failed: [172.16.122.130] => (item=ruby_deps) => {"failed": true, "item": "ruby_deps"}
msg: No package matching 'ruby_deps' is available

FATAL: all hosts have already failed -- aborting

Perhas these packages should be added since apt is used? autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

**Comment by leucos** [comment]
Mmm, travis hook not firing :(

**Comment by leucos** [comment]
Ok, Travis looks tired currently. In the meantime, thanks for reporting the issue @Veidit !

**Comment by Veidit** [comment]
Tested it on my machine and it works great, thanks!

**Comment by leucos** [comment]
cool !
