### ISSUE TITLE
Not working with ansible 1.9.0.1

### ISSUE THREAD

**Issue by scheffield** [erasme/ansible-ruby-compiled#3]
Hi,

on Ubuntu 14.04 it is impossible to get the .bashrc sourced via ssh. This leads to the following error

```
failed: [default] => {"ansible_job_id": "205827797946.13518", "changed": true, "cmd": "cd; bash -lc \"MAKEOPTS=-j2 CONFIGURE_OPTS=\"--disable-install-rdoc\" rbenv install 2.2.1\"", "delta": "0:00:00.009159", "end": "2015-04-04 10:56:30.894115", "finished": 1, "rc": 127, "start": "2015-04-04 10:56:30.884956", "warnings": []}
stderr: stdin: is not a tty
bash: rbenv: command not found
<job 205827797946.13518> FAILED on default
```

As I can see travis uses Ubuntu 12.04. for testing. So we could at least correct the listing of the supported Ubuntu version.

**Comment by leucos** [comment]
Hi @scheffield 
My guess is that you're running 1.9.0. Can you post what ansible version you're using ?

**Comment by leucos** [comment]
To elaborate on Ansible version problem (if it is the reason), there is a nasty bug in 1.9.0-x series where 'sudo' commands persists across tasks. It is fixed on devel, you might also want to try on this version to be sure.

**Comment by scheffield** [comment]
Hi, I can confirm that with ansible 1.8.4 your role works. So for the moment I will go with that ansible version. Thanks for your help.

**Comment by leucos** [comment]
No problem, thanks for testing. The next Ansible release will correct this (it is already fixed in devel).

**Comment by kmeister2000** [comment]
I ran into this issue with Ansible version 1.9.0.1 and can confirm that updating to 1.9.2 resolves the issue (OS X Mavericks / installed via Homebrew)

**Comment by leucos** [comment]
Thanks you for the update @kmeister2000 !
