### ISSUE TITLE
Dependency on ansible-rbenv not resolved

### ISSUE THREAD

**Issue by ghost** [erasme/ansible-ruby-compiled#4]
I installed both erasme.rbenv and erasme.ruby-compiled with galaxy. Then I added `- { role: erasme.ruby-compiled, ruby_version: "2.2.0" }` to my playbook.

Provisioning immediately fails with:
`ERROR: cannot find role in /home/bart/prj/gitlab-runner/roles/ansible-rbenv or /home/bart/prj/gitlab-runner/ansible-rbenv or /etc/ansible/roles/ansible-rbenv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

Did I miss something here?

**Comment by leucos** [comment]
Hey @bvdv 

In fact I don't use galaxy anymore (I only use the CLI tool to process my requirements.yml). I don't think Galaxy is usable right now. There are many problems it doesn't solve (for instance, proper dependency resolution, version pinning, problems  with gihub entreprise behin corporate firewalls, site availability, parsing failures, ...).

So now, when I write playbooks, I just:
- add `roles_path = ./.imported_roles:...some_other_path_if_needed` in my projects' `ansible.cfg`
- create a `requirements.yml` file containing all the requirements like so:

```
- name: ansible-rbenv
  src: https://github.com/erasme/ansible-rbenv.git

- name: ansible-ruby-compiled
  src: https://github.com/erasme/ansible-ruby-compiled.git
```
- in playbook(s), I just reference role by their names (no need to list dependencies) :

```
roles:
- ansible-ruby-compiled
  ruby_version: "2.2.0"
```

This is not ideal, it yields duplication (requirements/yml / roles meta/main.yml) but it is much much reliable to work this way than to rely on galaxy for me right now.

Sorry for the inconvenience if any, but I think role magament and dependency should become a first class citizen in Ansible, and currently, it is not. Recents announcements and changes are encouraging though.

**Comment by ghost** [comment]
Thank you very much for the very thorough explanation (and sharing the playbook in the first place!). That will certainly help me progress.
